appname: GraphSpace
layout: bootstrap
logger: file
#logger: console
session: YAML
serializer: JSON
charset: "UTF-8"

template: template_toolkit
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'

plugins:
    DBIC:
        graphdb:
            schema_class: 'GraphSpace::Schema'
            dsn: dbi:SQLite:dbname=/home/naveed/projects/GraphSpace/data/graph-space.db
            user: graphspace_db_user
            pass: graphspace_db_password
    #NYTProf:
        #profdir: ./profiles
