appname: Graph-Space
layout: main
logger: file
#logger: console

template: template_toolkit
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'

plugins:
    DBIC:
        graphdb:
            schema_class: 'GraphSpace::Schema'
            dsn: dbi:SQLite:dbname=/var/local/Graph-Space/graph-space.db

ppi_path: /var/local/Graph-Space/ppi/yeast_biogrid
