appname: GraphSpace
layout: bootstrap
logger: file
#logger: console
session: YAML
serializer: JSON
charset: "UTF-8"

template: template_toolkit
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'

plugins:
    DBIC:
        graphdb:
            schema_class: 'GraphSpace::Schema'
            dsn: dbi:SQLite:dbname=/home/naveed/projects/GraphSpace/data/graph-space.db
            #dsn: dbi:SQLite:dbname=/var/local/Graph-Space/graph-space.db

ppi_path: /var/local/Graph-Space/ppi/yeast_biogrid
