appname: GraphSpace
layout: bootstrap
session: YAML
serializer: JSON
charset: "UTF-8"

template: template_toolkit
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'

plugins:
    DBIC:
        default:
            schema_class: 'GraphSpace::Schema'
            dsn: dbi:SQLite:dbname=/var/graphspace.db
            user: graphspace_db_user
            pass: graphspace_db_password
    #NYTProf:
        #profdir: ./profiles
